name: Create Timestamp

on:
  push:
    branches:
      - main

jobs:
  write-timestamp:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up current date and time
      working-directory: ${{ github.workspace }}
      run: date +"%Y-%m-%d %H:%M:%S" > current_time.txt

    - name: Start app
      run: docker-compose up
        
